name: Template Pipeline

on:
  workflow_call:  # The workflow will be called by other repositories
    inputs:
      repo:
        type: string
        description: 'The Docker Repository name to push to'
        required: true
      tag:
        type: string
        description: 'The Docker Tag to push to'
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Dockerhub
        run: |
          docker build -t jimfaraj/${{ inputs.repo }}:${{ inputs.tag }} .
          docker push jimfaraj/${{ inputs.repo }}:${{ inputs.tag }}          

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Image
        run: |
          ssh -t ciuser@132.145.62.69
          docker pull jimfaraj/${{ inputs.repo }}:${{ inputs.tag }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

