on:
  workflow_call:
    inputs:
      repo:
        type: string
        description: The Docker Repository name to push to
        required: true
      tag:
        type: string
        description: The Docker Tag to push to
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      HOST:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: docker build -t {{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.repo }}:${{ inputs.tag }} .

      - name: Push Image
          docker push {{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.repo }}:${{ inputs.tag }}          

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ciuser
          port: 22
          script: docker pull {{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.repo }}:${{ inputs.tag }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
